apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: ap
  name: 99-gitops-ap
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          compression: ""
          source: data:text/plain;charset=utf-8;base64,aGVsbG8gd29ybGQ=
        mode: 420
        overwrite: true
        path: /etc/william-test
