apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    app.kubernetes.io/instance: machine-config
    machineconfiguration.openshift.io/role: ap
  name: 99-gitops-ap
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          compression: ""
          source: data:text/plain;charset=utf-8;base64,OTktenoK
        mode: 420
        overwrite: true
        path: /etc/william-test
